x-standalone-env: &standalone-env
  REDIS_ENABLED: "true"
  REDIS_URI: "redis://rdb:6379"

  ACTIO_MODE: "cluster"
  ACTIO_REGISTRY: "redis"
  ACTIO_NODE_WEIGHT: "1.0"

  JWT_SECRET_KEY: "Z2cNlGobkK9xseIPyyqq6PhT9c6hseaj"
  SECURE_COOKIES: "false"

services:
  rdb:
    image: redis:alpine
    ports:
      - "127.0.0.1:6379:6379"
    networks:
      - actio
    restart: always

  api1:
    image: actio-st:latest
    ports:
      - "5001:5000"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      <<: *standalone-env
      ACTIO_NODE_ID: "api1"
      ACTIO_NODE_WEIGHT: "1.0"
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ${PWD}/examples/cluster:/app/api:rw
      - ${PWD}/src/actio:/app/src/actio:rw
    command: /bin/bash -c "/env/bin/uvicorn api:app --ws auto --host 0.0.0.0 --port 5000 --reload --log-config ./api/logging.json"
    networks:
      - actio
    depends_on:
      - rdb
    restart: always

  api2:
    image: actio-st:latest
    ports:
      - "5002:5000"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      <<: *standalone-env
      ACTIO_NODE_ID: "api2"
      ACTIO_NODE_WEIGHT: "1.0"
    volumes:
      - ${PWD}/examples/cluster:/app/api:rw
      - ${PWD}/src/actio:/app/src/actio:rw
    command: /bin/bash -c "/env/bin/uvicorn api:app --ws auto --host 0.0.0.0 --port 5000 --reload --log-config ./api/logging.json"
    networks:
      - actio
    depends_on:
      - rdb
    restart: always

  api3:
    image: actio-st:latest
    ports:
      - "5003:5000"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      <<: *standalone-env
      ACTIO_NODE_ID: "api3"
      ACTIO_NODE_WEIGHT: "1.0"
    volumes:
      - ${PWD}/examples/cluster:/app/api:rw
      - ${PWD}/src/actio:/app/src/actio:rw
    command: /bin/bash -c "/env/bin/uvicorn api:app --ws auto --host 0.0.0.0 --port 5000 --reload --log-config ./api/logging.json"
    networks:
      - actio
    depends_on:
      - rdb
    restart: always

networks:
  actio:
    name: actio
